export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const VISIBILITY_FILTER = 'VISIBILITY_FILTER'
export const SHOW_TODO = 'todo'
export const SHOW_ALL = 'all'
export const SHOW_DONE = 'complete'
export const RECEIVE_TODOS = 'RECEIVE_TODOS'