export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const VISIBILITY_FILTER = 'VISIBILITY_FILTER'
export const SHOW_TODO = 'SHOW_TODO'
export const SHOW_ALL = 'SHOW_ALL'
export const SHOW_DONE = 'SHOW_DONE'